project:
  type: website
  preview:
    port: 5165

website:
  title: "PIFSC Glider Lab"
  site-url: "https://noaa-pifsc.github.io/glider-lab/" 
  repo-url: "https://github.com/noaa-pifsc/glider-lab/"
  repo-actions: [edit, source, issue]
  favicon: img/favicon.ico
  page-navigation: false
  back-to-top-navigation: true
  bread-crumbs: true
      
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; [CC0-1.0](https://github.com/noaa-pifsc/glider-lab/blob/main/LICENSE)"
  
  sidebar:
    background: $waves
    logo: "img/PSD.Dark.NoBackground.png"
    favicon: img/favicon.ico
    pinned: true
    align: center
    tools: 
      # - icon: globe
      #   href: https://nmfs-opensci.github.io
      #   text: "NMFS Open Science"
      - icon: github
        href: https://github.com/noaa-pifsc/glider-lab
        text: "PIFSC Glider Lab"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: missions.qmd
        text: Missions
      - section: Best practices
        contents:
        - href: best-practices.qmd
          text: Lab values & best practices
        - href: mission-prep.qmd
          text: Mission preparation
        - href: data-management.qmd
          text: Data management
        - href: data-processing.qmd
          text: Data processing
      - section: Piloting
        contents:
        - href: team-resources.qmd
          text: Team resources
        - href: oceanography.qmd
          text: Oceanography
      # - section: "Glider Lab"
      #   contents:
      #     - content/lab.qmd
      #     - content/pilot-tools.qmd
      # - section: "Data Processing"
      #   contents:
      #     - href: dataproc-gliders.qmd
      #       text: Gliders
      #     - href: dataproc-acoustics.qmd
      #       text: Acoustics
      - href: gliders.qmd
        text: Gliders
      - section: Sensors
        contents:
        - href: wispr.qmd
          text: WISPR passive acoustics

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 4
    link-external-newwindow: true
    embed-resources: true

filters:
  # - include-files.lua
  - quarto


